services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - ${DATA_DIR:-/opt/stacks/nginxproxymanager}/data:/data
      - ${DATA_DIR:-/opt/stacks/nginxproxymanager}/letsencrypt:/etc/letsencrypt

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    restart: unless-stopped
    environment:
      COLLECTIONS: crowdsecurity/nginx-proxy-manager
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.d/nginx-proxy-manager.yaml:ro
      - ${DATA_DIR:-/opt/stacks/nginxproxymanager}/data/logs:/var/log/nginx-proxy-manager:ro
      - ${DATA_DIR:-/opt/stacks/nginxproxymanager}/crowdsec/data:/var/lib/crowdsec/data
    depends_on:
      - app
