name: openwebui

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    network_mode: host
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    environment:
      - PORT=${OPEN_WEBUI_PORT:-8888}
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - WEB_SEARCH_RESULT_COUNT=${WEB_SEARCH_RESULT_COUNT:-3}
      - WEB_SEARCH_CONCURRENT_REQUESTS=${WEB_SEARCH_CONCURRENT_REQUESTS:-10}
      - SEARXNG_QUERY_URL=http://127.0.0.1:${SEARXNG_PORT:-8080}/search?q=<query>
      - HF_TOKEN=${HF_TOKEN}
    restart: always
    depends_on:
      searxng-core:
        condition: service_started
  searxng-core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:latest
    network_mode: host
    restart: always
    volumes:
      - ./searxng/core-config/:/etc/searxng/:Z
      - searxng-core-data:/var/cache/searxng/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      searxng-valkey:
        condition: service_started
  searxng-valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    network_mode: host
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    volumes:
      - searxng-valkey-data:/data/
volumes:
  open-webui:
  searxng-core-data:
  searxng-valkey-data:
