services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - '8082:8080'
    volumes:
      - ${STIRLING_DATA_DIR}/tessdata:/usr/share/tessdata  # OCR language files
      - ${STIRLING_DATA_DIR}/configs:/configs               # Settings & database
      - ${STIRLING_DATA_DIR}/logs:/logs                     # Application logs
      - ${STIRLING_DATA_DIR}/pipeline:/pipeline             # Automation configs
    environment:
      - SECURITY_ENABLELOGIN=false    # Set true to enable user authentication
      - LANGS=en_GB                   # Interface language
    restart: unless-stopped
