services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
      HOMEPAGE_VAR_RASPI_IP: ${HOMEPAGE_VAR_RASPI_IP}
      HOMEPAGE_VAR_NAS_IP: ${HOMEPAGE_VAR_NAS_IP}
      HOMEPAGE_VAR_COOLIFY_IP: ${HOMEPAGE_VAR_COOLIFY_IP}
      HOMEPAGE_VAR_PORTAINER_IP: ${HOMEPAGE_VAR_PORTAINER_IP}
      HOMEPAGE_VAR_JELLYFIN_IP: ${HOMEPAGE_VAR_JELLYFIN_IP}
      HOMEPAGE_VAR_OPENWEBUI_IP: ${HOMEPAGE_VAR_OPENWEBUI_IP}
    restart: unless-stopped
