services:
  backrest:
    image: ghcr.io/garethgeorge/backrest:v1.14.1
    container_name: backrest
    hostname: backrest
    volumes:
      - ${BACKREST_DATA_DIR}/data:/data
      - ${BACKREST_DATA_DIR}/config:/config
      - ${BACKREST_DATA_DIR}/cache:/cache
      - ${BACKREST_DATA_DIR}/tmp:/tmp
      - ${BACKREST_DATA_DIR}/rclone:/root/.config/rclone
      - ${BACKUP_SOURCE_PATH}:/userdata
      # - ${REPOS_PATH}:/repos
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=${TIMEZONE}
    ports:
      - "${BACKREST_PORT}:9898"
    restart: unless-stopped
