---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

layout:
  Core Infrastructure:
    style: row
    columns: 4
  Storage and Media:
    style: row
    columns: 4
  Media Stack:
    style: row
    columns: 4
  Apps:
    style: row
    columns: 4
  Backups:
    style: row
    columns: 4
  Finance:
    style: row
    columns: 2
  AI and Automation:
    style: row
    columns: 4
  Coolify Apps:
    style: row
    columns: 4

statusStyle: dot

