---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

layout:
  Core Infrastructure:
    style: row
    columns: 7
  Storage and Media:
    style: row
    columns: 4
  Media Stack:
    style: row
    columns: 6
  Apps:
    style: row
    columns: 5
  Finance:
    style: row
    columns: 2
  AI and Automation:
    style: row
    columns: 5
  Coolify Apps:
    style: row
    columns: 6

statusStyle: dot

