services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMELAB_PATH}/dockge/data:/app/data
      - ${HOMELAB_PATH}:${HOMELAB_PATH}
    environment:
      - DOCKGE_STACKS_DIR=${HOMELAB_PATH}
